# 1. Create a 3x3x3 array with random values 

In [3]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.32757915 0.24582598 0.60765933]
  [0.57975968 0.46488556 0.14717168]
  [0.81967396 0.35348002 0.02945582]]

 [[0.23528044 0.37834168 0.36818804]
  [0.98200673 0.87143039 0.44022489]
  [0.56252146 0.14705078 0.86282277]]

 [[0.86555368 0.19765456 0.62697977]
  [0.02286558 0.27595468 0.41878233]
  [0.15734895 0.38610747 0.20248084]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [18]:
a = np.diag(1+np.arange(4),k=-1)

print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [21]:
a = np.zeros((8,8),dtype=int)

a[1::2,::2] = 1

a[::2,1::2] = 1

print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [22]:
a = np.random.random((5,5))

amax, amin = a.max(), a.min()

a = (a - amin)/(amax - amin)

print(a)

[[0.16537572 0.0808872  0.79260145 0.50744326 0.59042652]
 [0.94804235 0.05848948 1.         0.39734049 0.15094613]
 [0.04188644 0.42189289 0.35505061 0.80371623 0.96071312]
 [0.07760313 0.57561667 0.02160888 0.55702121 0.0372269 ]
 [0.68723299 0.         0.02587591 0.51945579 0.78663657]]


# 5.  How to find common values between two arrays?

In [23]:
a1 = np.random.randint(0,10,10)

a2 = np.random.randint(0,10,10)

print(np.intersect1d(a1,a2))

[0 2 3 8]


# 6.How to get the dates of yesterday, today and tomorrow?

In [28]:
yesterday = np.timedelta64('today', 'D') - np.timedelta64(1, 'D')

today = np.datetime64('today', 'D')

tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(yesterday)

print(today)

print(tomorrow)

2020-07-28
2020-07-29
2020-07-30


# 7. Consider two random array A and B, check if they are equal

In [33]:
a = np.random.randint(0,1,5)
b = np.random.randint(0,1,5)
equal = np.allclose(a,b)
print('equal')
equal = np.array_equal(a,b)
print('equal')

equal
equal


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [34]:
Z = np.random.random(10)

Z[Z.argmax()] = 0

print(Z)

[0.37058356 0.         0.48671426 0.4186176  0.05663304 0.58280924
 0.82593446 0.34956129 0.08302605 0.67155097]


# 9. How to print all the values of an array?

In [39]:
import numpy as np
np.set_printoptions(threshold=np.nan)
x = np.zeros((4, 4))
print(x)

ValueError: ignored

# 10.Subtract the mean of each row of a matrix

In [40]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[ 0.04371776  0.35888955 -0.49663939 -0.20567989  0.30186561 -0.33682786
   0.43965322 -0.27440151  0.35951321 -0.19009071]
 [-0.35427115 -0.07927496  0.36770633 -0.14459954 -0.18196643  0.52847347
   0.15831638 -0.0947928   0.07094384 -0.27053515]
 [ 0.41554007  0.09216166  0.24558962 -0.07258739 -0.2973692   0.13181059
  -0.165147   -0.43132963 -0.29669371  0.378025  ]
 [-0.05161886  0.10554107 -0.47147902  0.42296449 -0.38225536 -0.36838285
   0.17661408  0.17680829 -0.01797137  0.40977953]
 [-0.38143929 -0.1034662  -0.45896018  0.48937383  0.00915669  0.18289768
   0.45829594 -0.15537806  0.333139   -0.3736194 ]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [41]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)
np.add.at(Z, I, 1)

[4. 7. 3. 3. 1. 2. 4. 4. 1. 1.]


# 12.How to get the diagonal of a dot product?

In [44]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))
np.sum(A * B.T, axis=1)
np.einsum("ij,ji->i", A, B)

array([2.46224179, 0.28422576, 0.44184559, 1.31331825, 0.37246953])

# 13.How to find the most frequent value in an array?

In [45]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

1


# 14.How to get the n largest values of an array

In [47]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [49]:
Z = np.array([("Hello", 2.5, 3),

("World", 3.6, 2)])

R = np.core.records.fromarrays(Z.T,names='col1, col2, col3',formats = 'S8, f8, i8')

print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
